#!/bin/bash
#
#kasutajad_failist_paroolid
#
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 kasutajad_failist_paroolid"
else
   kasutajanimed=$1
  if [ -f $kasutajanimed -a -r $kasutajanimed ]; then
echo "korras"
	for rida in $(cat $kasutajanimed)
	do
  kasutajanimi=$(echo "$rida" | cut -f1 -d:)
  sh lisa_kasutaja $kasutajanimi
  echo "$rida" | chpasswd
done
  else
	echo "probleem failiga $kasutajad_failist_paroolid"
  fi
fi
